Update CAS configuration to use ssl

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,7 +6,7 @@ variables:
   # directory.
   XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"
   GET_SOURCES_ATTEMPTS: 3
-  BST_CACHE_SERVER_ADDRESS: 'artifacts.freedesktop.codethink.co.uk'
+  BST_CACHE_SERVER_ADDRESS: 'testcache.codethink.co.uk'
   BST_RELEASES_SERVER_ADDRESS: 'cache.sdk.freedesktop.org'
   BST_CACHE_SSH_USER: 'artifacts'
 
@@ -47,10 +47,22 @@ before_script:
         ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
     fi
 
+  # Create CAS directory for SSL keys
+  - mkdir -p /etc/ssl/CAS
+ 
+  # Private SSL keys/certs for psuhing to the CAS server
+  - |
+    if [ -z "$GITLAB_CAS_PUSH_CERT" ]; then
+       echo >&2 "Private CAS cert not found"
+    else
+       echo "$GITLAB_CAS_PUSH_CERT" > /etc/ssl/CAS/server.crt
+       echo "$GITLAB_CAS_PUSH_KEY" > /etc/ssl/CAS/server.key
+    fi
+
   # Use internal network only if we are using x86_64 runners from DigitalOcean
   - |
     if [ "${CI_RUNNER_DESCRIPTION}" == 'manager-runner-freedesktop' ]; then
-        export BST_CACHE_SERVER_ADDRESS="${GITLAB_BST_CACHE_SERVER_IP}"
+        export BST_CACHE_SERVER_ADDRESS="${GITLAB_CAS_IP}"
         export BST_CACHE_SSH_USER='artifacts-internal'
     fi
 
@@ -65,11 +77,15 @@ before_script:
         echo "projects:" > ~/.config/buildstream.conf
         echo "  base-sdk-bootstrap:" >> ~/.config/buildstream.conf
         echo "    artifacts:" >> ~/.config/buildstream.conf
-        echo "      url: ssh://${BST_CACHE_SSH_USER}@${BST_CACHE_SERVER_ADDRESS}/artifacts/" >> ~/.config/buildstream.conf
+        echo "      url: https://${BST_CACHE_SERVER_ADDRESS}/artifacts/" >> ~/.config/buildstream.conf
+        echo "      client-key: /etc/ssl/CAS/server.key" >> ~/.config/buildstream.conf
+        echo "      client-cert: /etc/ssl/CAS/server.crt" >> ~/.config/buildstream.conf
         echo "      push: true" >> ~/.config/buildstream.conf
         echo "  base-sdk:" >> ~/.config/buildstream.conf
         echo "    artifacts:" >> ~/.config/buildstream.conf
-        echo "      url: ssh://${BST_CACHE_SSH_USER}@${BST_CACHE_SERVER_ADDRESS}/artifacts/" >> ~/.config/buildstream.conf
+        echo "      url: https://${BST_CACHE_SERVER_ADDRESS}/artifacts/" >> ~/.config/buildstream.conf
+        echo "      client-key: /etc/ssl/CAS/server.key" >> ~/.config/buildstream.conf
+        echo "      client-cert: /etc/ssl/CAS/server.crt" >> ~/.config/buildstream.conf
         echo "      push: true" >> ~/.config/buildstream.conf
     fi
 
